# Generated by Django 2.1.5 on 2019-03-17 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Happyhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(verbose_name='Address')),
                ('time_start', models.DateTimeField(db_index=True)),
                ('time_end', models.DateTimeField(db_index=True)),
                ('added', models.DateTimeField(default=datetime.datetime(2019, 3, 17, 17, 1, 34, 738871))),
            ],
        ),
    ]
