# Generated by Django 2.1.5 on 2019-03-17 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 17, 7, 34, 913013, tzinfo=utc)),
        ),
    ]
