# Generated by Django 2.1.5 on 2019-03-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190318_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='added',
            field=models.DateField(verbose_name='Date review added/updated'),
        ),
    ]
