# Generated by Django 2.1.5 on 2019-03-17 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190317_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhour',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
